"""Create the log table

Revision ID: 1a210127a74b
Revises: 
Create Date: 2026-06-08 12:55:39.524620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a210127a74b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('emitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('service', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('massage', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('trace_id', sa.String(length=128), nullable=True),
    sa.Column('request_id', sa.String(length=50), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_logs'))
    )
    op.create_index(op.f('ix_logs_emitted_at'), 'logs', ['emitted_at'], unique=False)
    op.create_index(op.f('ix_logs_environment'), 'logs', ['environment'], unique=False)
    op.create_index(op.f('ix_logs_host'), 'logs', ['host'], unique=False)
    op.create_index(op.f('ix_logs_level'), 'logs', ['level'], unique=False)
    op.create_index('ix_logs_level_emitted_at', 'logs', ['level', 'emitted_at'], unique=False)
    op.create_index(op.f('ix_logs_request_id'), 'logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_logs_service'), 'logs', ['service'], unique=False)
    op.create_index('ix_logs_service_emitted_at', 'logs', ['service', 'emitted_at'], unique=False)
    op.create_index(op.f('ix_logs_trace_id'), 'logs', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_trace_id'), table_name='logs')
    op.drop_index('ix_logs_service_emitted_at', table_name='logs')
    op.drop_index(op.f('ix_logs_service'), table_name='logs')
    op.drop_index(op.f('ix_logs_request_id'), table_name='logs')
    op.drop_index('ix_logs_level_emitted_at', table_name='logs')
    op.drop_index(op.f('ix_logs_level'), table_name='logs')
    op.drop_index(op.f('ix_logs_host'), table_name='logs')
    op.drop_index(op.f('ix_logs_environment'), table_name='logs')
    op.drop_index(op.f('ix_logs_emitted_at'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
