"""corrected the column name from massage to message

Revision ID: f6ad8edebe35
Revises: 1a210127a74b
Create Date: 2026-06-09 16:11:49.789244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ad8edebe35'
down_revision: Union[str, Sequence[str], None] = '1a210127a74b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('message', sa.Text(), nullable=False))
    op.drop_column('logs', 'massage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('massage', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('logs', 'message')
    # ### end Alembic commands ###
